server:
  port: ${SERVER_PORT:4000}
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers
  writer-with-order-by-keys: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Dev Test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:tasks}${DB_OPTIONS:}
    username: ${DB_USER_NAME:tasks}
    password: ${DB_PASSWORD:tasks}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: TasksHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
